"""
app.py — Streamlit interface for The Unofficial Guide (Milestone 5).

Chat input -> retrieve -> grounded Groq answer with expandable source panels.
"""

from __future__ import annotations

import streamlit as st

from generate import generate_answer
from retrieve import DEFAULT_TOP_K, get_collection, get_embedding_model
from source_links import load_manifest, url_for

st.set_page_config(
    page_title="The Unofficial Guide",
    page_icon="📚",
    layout="wide",
)

st.title("The Unofficial Guide")
st.caption(
    "Grounded CS course advice for UMass Amherst — answers cite retrieved sources only."
)


@st.cache_resource
def load_retrieval_stack():
    """Load embedding model and Chroma collection once per session."""
    get_embedding_model()
    get_collection(reset=False)
    return True


@st.cache_resource
def get_source_manifest():
    return load_manifest()


def render_sources(sources: list[dict]) -> None:
    with st.expander("Sources used", expanded=False):
        manifest = get_source_manifest()
        for source in sources:
            metadata = source["metadata"]
            header = source.get("citation_header") or metadata.get("source_file", "")
            citation_url = source.get("citation_url") or url_for(
                str(metadata.get("source_file", "")), manifest
            )

            st.markdown(f"**[{source['rank']}] {header}**")
            if citation_url:
                st.markdown(f"[Open source]({citation_url})")

            meta_bits = [
                f"type: {metadata.get('source_type', '—')}",
                f"distance: {source['distance']:.4f}",
                f"adjusted: {source.get('adjusted_distance', source['distance']):.4f}",
                f"audience: {metadata.get('audience', '—')}",
            ]
            if metadata.get("semester"):
                meta_bits.append(f"semester: {metadata['semester']}")
            if metadata.get("course_code"):
                meta_bits.append(f"course: {metadata['course_code']}")
            if metadata.get("professor"):
                meta_bits.append(f"professor: {metadata['professor']}")
            if metadata.get("thread_title"):
                meta_bits.append(f"thread: {metadata['thread_title']}")
            st.caption(" · ".join(meta_bits))
            st.text(source["text"][:1200] + ("..." if len(source["text"]) > 1200 else ""))
            st.divider()


with st.sidebar:
    st.header("Settings")
    top_k = st.slider("Top-k chunks", min_value=3, max_value=10, value=DEFAULT_TOP_K)
    st.markdown("---")
    st.markdown(
        "Answers are generated by **Groq llama-3.3-70b** using only retrieved chunks. "
        "If the sources don't contain enough information, the assistant refuses to guess."
    )

load_retrieval_stack()
get_source_manifest()

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        if message.get("sources"):
            render_sources(message["sources"])

if prompt := st.chat_input("Ask about CS courses, professors, or schedules..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving and generating..."):
            try:
                result = generate_answer(prompt, top_k=top_k)
                answer = result["linked_answer"]
                sources = result["cited_sources"]
            except RuntimeError as exc:
                answer = f"**Error:** {exc}"
                sources = []
            except Exception as exc:
                answer = f"**Unexpected error:** {exc}"
                sources = []

        st.markdown(answer)
        if sources:
            render_sources(sources)

    st.session_state.messages.append(
        {"role": "assistant", "content": answer, "sources": sources}
    )
